table Parashiyos
	excludeFromModelRefresh
	lineageTag: c19d6d93-efea-406d-b99d-085f8bae3303

	column Sefer
		dataType: string
		lineageTag: db7b3b18-f3f2-4cc3-a197-1d2bd426900f
		summarizeBy: none
		sourceColumn: Sefer

		annotation SummarizationSetBy = Automatic

	column Book
		dataType: string
		lineageTag: 1631e0e2-ceb9-412d-936b-551638bfc4a7
		summarizeBy: none
		sourceColumn: Book

		annotation SummarizationSetBy = Automatic

	column Parasha
		dataType: string
		lineageTag: 89acad91-dd3a-4432-94e5-142c00d9b3c8
		summarizeBy: none
		sourceColumn: Parasha
		sortByColumn: Index_Parasha

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Start
		dataType: string
		lineageTag: 3f4f90bd-4c28-485e-88e6-b4f371d5e789
		summarizeBy: none
		sourceColumn: Start

		annotation SummarizationSetBy = Automatic

	column End
		dataType: string
		lineageTag: b70ce547-d02b-4a87-8a2b-6029ebd4b0b8
		summarizeBy: none
		sourceColumn: End

		annotation SummarizationSetBy = Automatic

	column StartChapter
		dataType: int64
		formatString: 0
		lineageTag: 62602fde-0877-4b4b-8577-1a200f560ee1
		summarizeBy: none
		sourceColumn: StartChapter

		annotation SummarizationSetBy = User

	column StartVerse
		dataType: int64
		formatString: 0
		lineageTag: 40d64ac4-a401-470d-ab38-c7a826d2b124
		summarizeBy: none
		sourceColumn: StartVerse

		annotation SummarizationSetBy = User

	column EndChapter
		dataType: int64
		formatString: 0
		lineageTag: fd38bad8-641e-4b4e-8394-dcf3470a4030
		summarizeBy: none
		sourceColumn: EndChapter

		annotation SummarizationSetBy = User

	column EndVerse
		dataType: int64
		formatString: 0
		lineageTag: 0288d05e-94f1-4fca-9113-8fff70ce84bc
		summarizeBy: none
		sourceColumn: EndVerse

		annotation SummarizationSetBy = User

	column Verses
		dataType: int64
		formatString: 0
		lineageTag: 92e3a102-51a7-40f0-9c44-e5c202513d0c
		summarizeBy: none
		sourceColumn: Verses

		annotation SummarizationSetBy = User

	column Index_BookParasha
		dataType: int64
		formatString: 0
		lineageTag: b6912ed5-25e2-4e81-b44d-c978855801b0
		summarizeBy: none
		sourceColumn: Index_BookParasha

		annotation SummarizationSetBy = User

	column Index_Parasha
		dataType: int64
		formatString: 0
		lineageTag: d7fad80c-ddad-4004-bbf9-48515719e2bf
		summarizeBy: none
		sourceColumn: Index_Parasha

		annotation SummarizationSetBy = User

	column Doubled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1c29ad07-9fbf-462e-9d32-5f8749408f29
		summarizeBy: none
		sourceColumn: Doubled

		annotation SummarizationSetBy = Automatic

	/// Loads static parasha boundaries and derives chapter/verse coordinates plus semantic indexes in Power Query.
	partition Parashiyos = m
		mode: import
		queryGroup: Chumash
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://raw.githubusercontent.com/posnerab/torah-data/main/Torah.xlsx"), null, true),
				    ParashiyosTable = Source{[Item="Parashiyos",Kind="Table"]}[Data],
				    BaseColumns = Table.RemoveColumns(
				        ParashiyosTable,
				        {"StartChapter", "StartVerse", "EndChapter", "EndVerse"},
				        MissingField.Ignore
				    ),
				    TypedBase = Table.TransformColumnTypes(
				        BaseColumns,
				        {{"Sefer", type text}, {"Book", type text}, {"Parasha", type text}, {"Start", type text}, {"End", type text}, {"Verses", Int64.Type}, {"Doubled", type logical}}
				    ),
				    WithStartChapter = Table.AddColumn(TypedBase, "StartChapter", each Int64.From(Number.FromText(Text.BeforeDelimiter([Start], ":"))), Int64.Type),
				    WithStartVerse = Table.AddColumn(WithStartChapter, "StartVerse", each Int64.From(Number.FromText(Text.AfterDelimiter([Start], ":"))), Int64.Type),
				    WithEndChapter = Table.AddColumn(WithStartVerse, "EndChapter", each Int64.From(Number.FromText(Text.BeforeDelimiter([End], ":"))), Int64.Type),
				    WithEndVerse = Table.AddColumn(WithEndChapter, "EndVerse", each Int64.From(Number.FromText(Text.AfterDelimiter([End], ":"))), Int64.Type),
				    Grouped = Table.Group(
				        WithEndVerse,
				        {"Sefer"},
				        {{"Rows", each Table.AddIndexColumn(_, "Index_BookParasha", 1, 1, Int64.Type), type table}}
				    ),
				    Expanded = Table.ExpandTableColumn(
				        Grouped,
				        "Rows",
				        {"Book", "Parasha", "Start", "End", "StartChapter", "StartVerse", "EndChapter", "EndVerse", "Verses", "Doubled", "Index_BookParasha"},
				        {"Book", "Parasha", "Start", "End", "StartChapter", "StartVerse", "EndChapter", "EndVerse", "Verses", "Doubled", "Index_BookParasha"}
				    ),
				    WithParashaIndex = Table.AddIndexColumn(Expanded, "Index_Parasha", 1, 1, Int64.Type),
				    Reordered = Table.ReorderColumns(
				        WithParashaIndex,
				        {"Sefer", "Book", "Parasha", "Start", "End", "StartChapter", "StartVerse", "EndChapter", "EndVerse", "Verses", "Index_BookParasha", "Index_Parasha", "Doubled"}
				    )
				in
				    Reordered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

